name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test
      - name: Publish BotFramework to NuGet
        uses: alirezanet/publish-nuget@v3
        with:
          PROJECT_FILE_PATH: BotFramework/BotFramework.csproj
          PACKAGE_NAME: BotFramework.NET
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: Publish BotFramework Previewer to NuGet
        uses: alirezanet/publish-nuget@v3
        with:
          PROJECT_FILE_PATH: BotFramework/BotFramework.Previewer.csproj
          PACKAGE_NAME: BotFramework.NET.Previewer
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}